//! Property-based tests for the folder-group pure-logic seam (Step 03-03).
//!
//! Pins three invariants from
//! `docs/feature/folder-group-bulk-delete/distill/features/`:
//!
//! - **AC-13 / M3 @property** (`folder-group-delete.feature`):
//!   `classify_unique_vs_shared` is the SINGLE source of truth for shared-vs-
//!   unique decisions on folder children. For every model in every generated
//!   `FolderGroup`, the bucket it lands in MUST match what
//!   `compute_indicator` returned: `Shared → shared` (with the same
//!   `other_tools` set), `Compatible | FormatLocked | Unknown → unique`.
//!
//! - **INT-FGD-2 @property** (`integration-checkpoints.feature`):
//!   For any generated `FolderGroup`,
//!   `folder.file_count() == models.len() + sidecars.len()`.
//!
//! - **INT-FGD-3 @property** (`integration-checkpoints.feature`):
//!   For any generated `FolderClassification` and the resulting
//!   `FolderDeletePlan`,
//!   `bytes_to_reclaim + bytes_to_retain == folder.total_bytes()` within a
//!   1-byte rounding tolerance.
//!
//! Plus an R1 mitigation invariant pinning ADR-002's conservative-when-
//! uncertain rule at the folder-classification layer: a model whose
//! `dedup_key` is `Tentative` MUST NEVER be classified as `Shared` (because
//! `compute_indicator` cannot confidently match without SHA256).
//!
//! ## Test budget (per quality-framework)
//!
//! Distinct behaviors pinned:
//!   B1: classification matches compute_indicator for every child (AC-13)
//!   B2: `other_tools` set on shared models matches the dedup-peer set
//!   B3: `folder.file_count() == models.len() + sidecars.len()` (INT-FGD-2)
//!   B4: `bytes_to_reclaim + bytes_to_retain == folder.total_bytes()` (INT-FGD-3)
//!   B5: Tentative dedup_key never yields Shared (R1 / ADR-002)
//!
//! Budget = 5 × 2 = 10 proptests max. We use 4 (B1+B2 share one proptest
//! because they assert co-variant properties on the same draw).
//!
//! ## Why these come up green on first run
//!
//! The production impl from Step 01-02 already enforces these invariants by
//! construction. These proptests are *regression coverage* — they fail loudly
//! the day someone tries to bypass `compute_indicator`, drift the file-count
//! arithmetic, or break the reclaim-math seam.

use std::collections::BTreeMap;
use std::path::PathBuf;

use modeltap_core::domain::RowIndicator;
use modeltap_core::logic::compatibility::{
    compute_indicator, Inventory, InventoryEntry, PluginCapabilityMap,
};
use modeltap_core::logic::folder_group::{build_folder_delete_plan, classify_unique_vs_shared};
use modeltap_core::types::{DedupKey, FolderGroup, ModelMeta, Sidecar, SidecarKind};
use modeltap_core::{ContentHash, DiscoveredModel, DisplayLabel, Format, ModelStatus, ToolId};
use proptest::prelude::*;

const HASH_A: ContentHash = ContentHash([0xAA; 32]);
const HASH_B: ContentHash = ContentHash([0xBB; 32]);
const HASH_C: ContentHash = ContentHash([0xCC; 32]);

// Bound generated byte sizes well under u64::MAX / N so summed totals cannot
// overflow during `folder.total_bytes()`. With <= 8 models + 8 sidecars per
// folder and per-file sizes <= 1 << 40 (~1 TiB), the maximum total is
// 16 × 2^40 = 2^44, far below u64::MAX.
const MAX_FILE_BYTES: u64 = 1 << 40;

// ---------------------------------------------------------------------------
// Strategies
// ---------------------------------------------------------------------------

prop_compose! {
    fn arb_format()(idx in 0u8..8u8) -> Format {
        match idx {
            0 => Format::Gguf,
            1 => Format::Safetensors,
            2 => Format::Bin,
            3 => Format::Awq,
            4 => Format::Gptq,
            5 => Format::OllamaBlob,
            6 => Format::Mlx,
            _ => Format::Other,
        }
    }
}

prop_compose! {
    /// Three named other-tools plus the implicit "hf" the folder is owned by.
    /// Bounded set so peers can collide and the dedup-peer count is meaningful.
    fn arb_other_tool()(idx in 0u8..3u8) -> &'static str {
        match idx {
            0 => "ollama",
            1 => "llama-cli",
            _ => "lm-studio",
        }
    }
}

prop_compose! {
    /// Authoritative `Content(hash)` ~2/3 of the time, `Tentative(label)`
    /// otherwise. Tentative keys exercise the R1 / ADR-002 conservative rule.
    fn arb_dedup_key()(idx in 0u8..3u8, label_seed in 0u32..16u32) -> DedupKey {
        match idx {
            0 => DedupKey::Content(HASH_A),
            1 => DedupKey::Content(HASH_B),
            _ => DedupKey::Tentative(DisplayLabel::from(format!("label-{label_seed}"))),
        }
    }
}

prop_compose! {
    /// A model belonging to the HF folder. `id_in_tool` is forced into the
    /// canonical `<author>/<repo>/<file>` shape so it survives `group_by_hf_repo`
    /// (not exercised here, but keeps the shape realistic).
    fn arb_hf_model(repo: String)(
        file_idx in 0u32..8u32,
        format in arb_format(),
        size_bytes in 1u64..MAX_FILE_BYTES,
        dedup_key in arb_dedup_key(),
    ) -> ModelMeta {
        let id = format!("{repo}/file-{file_idx}.gguf");
        let path = PathBuf::from(format!("/hf/cache/{}", id.replace('/', "--")));
        ModelMeta {
            tool: ToolId("hf"),
            id_in_tool: id.clone(),
            on_disk_path: path,
            size_bytes,
            format,
            display_label: DisplayLabel::from(id),
            status: ModelStatus::Healthy,
            dedup_key,
        }
    }
}

prop_compose! {
    fn arb_sidecar(repo: String)(
        idx in 0u32..8u32,
        size_bytes in 0u64..MAX_FILE_BYTES,
        kind_idx in 0u8..5u8,
    ) -> Sidecar {
        let kind = match kind_idx {
            0 => SidecarKind::Readme,
            1 => SidecarKind::Imatrix,
            2 => SidecarKind::Urls,
            3 => SidecarKind::HfInternal,
            _ => SidecarKind::Other,
        };
        Sidecar {
            path: PathBuf::from(format!("/hf/cache/{}--sidecar-{idx}", repo.replace('/', "--"))),
            size_bytes,
            kind,
        }
    }
}

prop_compose! {
    /// A canonical `<author>/<repo>` string with bounded variability so peer
    /// inventories can collide on dedup keys without exploding the search space.
    fn arb_repo()(
        author_idx in 0u8..3u8,
        repo_idx in 0u8..3u8,
    ) -> String {
        let author = match author_idx {
            0 => "bartowski",
            1 => "TheBloke",
            _ => "meta-llama",
        };
        let repo = match repo_idx {
            0 => "Llama-3.2-1B-Instruct-GGUF",
            1 => "Mistral-7B-Instruct-v0.2-GGUF",
            _ => "Mixtral-8x7B-Instruct-v0.1-GGUF",
        };
        format!("{author}/{repo}")
    }
}

prop_compose! {
    fn arb_folder_group()(repo in arb_repo())(
        models in prop::collection::vec(arb_hf_model(repo.clone()), 0..8),
        sidecars in prop::collection::vec(arb_sidecar(repo.clone()), 0..8),
        repo in Just(repo),
    ) -> FolderGroup {
        let absolute_path = PathBuf::from(format!("/hf/cache/models--{}", repo.replace('/', "--")));
        FolderGroup::new(
            repo,
            absolute_path,
            ToolId("hf"),
            models,
            sidecars,
        )
        .expect("arb_folder_group: canonical inputs by construction")
    }
}

prop_compose! {
    /// A peer inventory entry that may share a dedup key with one of the
    /// folder's models. Mixes hashes from `{HASH_A, HASH_B, HASH_C}` and tools
    /// from `{ollama, llama-cli, lm-studio}` so the engine can find or miss
    /// peers organically.
    fn arb_peer_entry()(
        tool in arb_other_tool(),
        hash_idx in 0u8..4u8,
        format in arb_format(),
        id_seed in 0u32..1000u32,
    ) -> InventoryEntry {
        let id = format!("peer-{id_seed}");
        let model = DiscoveredModel {
            id_in_tool: id.clone(),
            on_disk_path: PathBuf::from(format!("/{tool}/store/{id}")),
            size_bytes: 1_000_000,
            format,
            display_label: DisplayLabel::from(id),
            status: ModelStatus::Healthy,
        };
        let content_hash = match hash_idx {
            0 => Some(HASH_A),
            1 => Some(HASH_B),
            2 => Some(HASH_C),
            _ => None,
        };
        InventoryEntry {
            tool: ToolId(tool),
            model,
            content_hash,
        }
    }
}

prop_compose! {
    fn arb_caps()(
        ollama in prop::collection::vec(arb_format(), 0..3),
        llama_cli in prop::collection::vec(arb_format(), 0..3),
        hf in prop::collection::vec(arb_format(), 0..6),
        lm_studio in prop::collection::vec(arb_format(), 0..3),
    ) -> PluginCapabilityMap {
        let mut m: PluginCapabilityMap = BTreeMap::new();
        m.insert(ToolId("ollama"), ollama);
        m.insert(ToolId("llama-cli"), llama_cli);
        m.insert(ToolId("hf"), hf);
        m.insert(ToolId("lm-studio"), lm_studio);
        m
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Project a folder's `ModelMeta` back into the `InventoryEntry` shape that
/// `compute_indicator` expects, mirroring the private helper in
/// `logic::folder_group::inventory_entry_for`. Kept separate from that helper
/// to avoid coupling the test to a private function — this is intentional
/// duplication of the projection, not the classification rule itself.
fn project_model(model: &ModelMeta) -> InventoryEntry {
    let content_hash = match &model.dedup_key {
        DedupKey::Content(hash) => Some(*hash),
        DedupKey::Tentative(_) => None,
    };
    InventoryEntry {
        tool: model.tool,
        model: DiscoveredModel {
            id_in_tool: model.id_in_tool.clone(),
            on_disk_path: model.on_disk_path.clone(),
            size_bytes: model.size_bytes,
            format: model.format,
            display_label: model.display_label.clone(),
            status: model.status.clone(),
        },
        content_hash,
    }
}

// ---------------------------------------------------------------------------
// Proptests
// ---------------------------------------------------------------------------

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 256,
        .. ProptestConfig::default()
    })]

    /// **AC-13 / M3 @property**: every model the classifier puts in `shared`
    /// MUST be a model that `compute_indicator` calls `Shared`, and every
    /// model in `unique` MUST be one of `{Compatible, FormatLocked, Unknown}`.
    /// Additionally, for every shared model the `other_tools` set MUST equal
    /// the distinct tools whose inventory entries share a dedup-key with the
    /// target (the peer-listing rule must align with the Shared-decision rule,
    /// preserving the single-engine invariant D-FGD-4).
    #[test]
    fn classification_matches_compute_indicator_for_every_child(
        folder in arb_folder_group(),
        peers in prop::collection::vec(arb_peer_entry(), 0..6),
        cap in arb_caps(),
    ) {
        // Build the full inventory: every folder model plus the random peers.
        let mut entries: Vec<InventoryEntry> =
            folder.models.iter().map(project_model).collect();
        entries.extend(peers);
        let inv = Inventory { entries };

        let classification = classify_unique_vs_shared(&folder, &inv, &cap);

        // Every shared bucket entry must independently classify as Shared,
        // and its `other_tools` must match the engine's peer set.
        for shared in &classification.shared {
            let target = project_model(&shared.model);
            let indicator = compute_indicator(&target, &inv, &cap);
            prop_assert_eq!(
                indicator,
                RowIndicator::Shared,
                "shared-bucket model must compute_indicator → Shared (single-engine D-FGD-4)"
            );

            // Independent recomputation of the peer set, mirroring
            // `peer_tools_sharing` in production: any peer in a DIFFERENT tool
            // with matching `Some(hash)` content.
            let expected_peers: Vec<ToolId> = inv
                .entries
                .iter()
                .filter(|e| e.tool != target.tool)
                .filter(|e| match (target.content_hash, e.content_hash) {
                    (Some(a), Some(b)) => a == b,
                    _ => false,
                })
                .fold(Vec::<ToolId>::new(), |mut acc, e| {
                    if !acc.contains(&e.tool) {
                        acc.push(e.tool);
                    }
                    acc
                });

            prop_assert_eq!(
                &shared.other_tools, &expected_peers,
                "other_tools must match the dedup-peer set (peer-listing == Shared-decision)"
            );
            prop_assert!(
                !shared.other_tools.is_empty(),
                "a Shared classification implies at least one other tool"
            );
        }

        // Every unique bucket entry must independently classify as one of
        // Compatible / FormatLocked / Unknown — NEVER Shared.
        for model in &classification.unique {
            let target = project_model(model);
            let indicator = compute_indicator(&target, &inv, &cap);
            prop_assert!(
                matches!(
                    indicator,
                    RowIndicator::Compatible
                        | RowIndicator::FormatLocked
                        | RowIndicator::Unknown
                ),
                "unique-bucket model must compute_indicator ∈ {{Compatible, FormatLocked, Unknown}}, got {:?}",
                indicator
            );
        }

        // Partition completeness: every folder model lands in exactly one bucket.
        prop_assert_eq!(
            classification.unique.len() + classification.shared.len(),
            folder.models.len(),
            "classification must partition folder.models (no drops, no duplicates)"
        );
    }
}

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 256,
        .. ProptestConfig::default()
    })]

    /// **INT-FGD-2 @property**: `folder.file_count() == models.len() + sidecars.len()`.
    ///
    /// Trivial by construction, but pinned as a proptest so anyone who later
    /// refactors `FolderGroup::file_count` to (say) cache a precomputed value
    /// or to apply a "skip hidden sidecars" filter trips this gate before the
    /// reclaim-math seam silently drifts.
    #[test]
    fn file_count_equals_models_plus_sidecars(folder in arb_folder_group()) {
        prop_assert_eq!(
            folder.file_count(),
            folder.models.len() + folder.sidecars.len()
        );
    }
}

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 256,
        .. ProptestConfig::default()
    })]

    /// **INT-FGD-3 @property**: `bytes_to_reclaim + bytes_to_retain == folder.total_bytes()`
    /// within 1-byte rounding tolerance.
    ///
    /// Construct the full plan via the production `build_folder_delete_plan`
    /// over a random `(folder, inventory, capabilities)` draw. The plan's
    /// smart constructor enforces the tolerance, so a violation would have
    /// panicked at construction; we additionally assert here to surface the
    /// concrete arithmetic relation in the failure output for a human
    /// reviewer.
    #[test]
    fn reclaim_plus_retain_equals_total_bytes_within_one_byte(
        folder in arb_folder_group(),
        peers in prop::collection::vec(arb_peer_entry(), 0..6),
        cap in arb_caps(),
    ) {
        let mut entries: Vec<InventoryEntry> =
            folder.models.iter().map(project_model).collect();
        entries.extend(peers);
        let inv = Inventory { entries };

        let classification = classify_unique_vs_shared(&folder, &inv, &cap);
        let plan = build_folder_delete_plan(&folder, &classification);

        let total = folder.total_bytes();
        let sum = plan.bytes_to_reclaim.saturating_add(plan.bytes_to_retain);
        prop_assert!(
            sum.abs_diff(total) <= 1,
            "reclaim ({}) + retain ({}) = {} must equal total ({}) within 1-byte tolerance",
            plan.bytes_to_reclaim,
            plan.bytes_to_retain,
            sum,
            total
        );

        // Path-count invariant (data-models §4): full-unlink paths + HF-only
        // paths == models.len() + sidecars.len(). Co-pinned here so a future
        // refactor cannot drift the byte math and the path math independently.
        prop_assert_eq!(
            plan.paths_to_unlink_fully.len() + plan.paths_to_unlink_hf_only.len(),
            folder.file_count(),
            "path counts must sum to folder.file_count()"
        );
    }
}

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 256,
        .. ProptestConfig::default()
    })]

    /// **R1 / ADR-002 conservative-when-uncertain**: a model whose
    /// `dedup_key` is `Tentative` MUST NEVER appear in the `shared` bucket.
    ///
    /// `compute_indicator` refuses to call two entries shared when either
    /// side's SHA256 is `None`; `classify_unique_vs_shared` MUST inherit
    /// that property by routing through `compute_indicator`. This proptest
    /// pins the inheritance — if someone adds a shadow "label-equality
    /// fallback" inside the folder-group module that bypasses the engine,
    /// it would flip Tentative models into `shared` and this property would
    /// fail loudly.
    #[test]
    fn tentative_dedup_key_never_lands_in_shared_bucket(
        folder in arb_folder_group(),
        peers in prop::collection::vec(arb_peer_entry(), 0..6),
        cap in arb_caps(),
    ) {
        let mut entries: Vec<InventoryEntry> =
            folder.models.iter().map(project_model).collect();
        entries.extend(peers);
        let inv = Inventory { entries };

        let classification = classify_unique_vs_shared(&folder, &inv, &cap);

        for shared in &classification.shared {
            prop_assert!(
                matches!(shared.model.dedup_key, DedupKey::Content(_)),
                "Tentative dedup_key must NEVER be classified Shared (ADR-002 conservative); \
                 offending model id_in_tool={}",
                shared.model.id_in_tool
            );
        }
    }
}
